# Numpy
Numpay help us to store value in array like normal array,2D array or 3D, it's even faster than list. So, that's why we use numpy rather than a list. Because it's use less bytes of memory than a list. Another reason is that numpy doesn't check type of value in a array when we iterating it

Not only storing data, we can also use numpy for mathmathical calculation, drawing plots and it also backbone of some of the popular python pakage like pandas, connect 4 etc

In [487]:
import numpy as np #importing numpy 

In [488]:
a = np.array([1,2,3,4,5]) # np.array is used to create an array
print(a)

[1 2 3 4 5]


In [489]:
b = np.array([[9.0,8,9,4],[6.0,50,56,5.2]]) # creating a 2D array
print(b)

[[ 9.   8.   9.   4. ]
 [ 6.  50.  56.   5.2]]


In [490]:
# get the dimension of numpy array
print(a.ndim) # a.ndim use to get the number of dimension of an array

1


In [491]:
print(b.ndim)

2


In [492]:
print(a.shape) # a.shape tell us the shape of our data in array, in this 1D array shape is (4,) means out data is divided in 4 blocks because we have 4 values

(5,)


In [493]:
print(b.shape) # for 2D array , it's shape is like a matrix. in this case out data is divided into 2 rows and 4 columns

(2, 4)


In [494]:
print(a.dtype) # it's give us the data type so we can understand how much memory it's consuming, like in this case a array is int32

int32


In [495]:
print(b.dtype)

float64


In [496]:
print(a.itemsize) # a.itemsize give us length of one array element inbytes

4


In [497]:
print(b.itemsize) 

8


In [498]:
print(a.nbytes) # nbytes return total number of bytes consume by the array

20


In [499]:
print(b.nbytes)

64


In [500]:
print(a.size) # gives use total number of element 

5


In [501]:
print(b.size)

8


## accesing and changing elements , rows and colums

In [502]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,14,16]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 14 16]]


In [503]:
print(a.shape)

(2, 7)


In [504]:
# get a sepcific element in a 2D numpy array
print(a[1,0]) # numby indexing first item is row and sencond is column , remember indexing start with 0, for second row indexing is 1 and first column is 0

8


In [505]:
print(a[1,-1]) # you can also use negative value to choose last value, here -1 means last column

16


In [506]:
print(a[-1,-1])

16


In [507]:
#get a specific row
print(a[0,:]) # ":" means select every item, in this case select every colum in 0 array

[1 2 3 4 5 6 7]


In [508]:
print(a[:,0]) # select every row in first column

[1 8]


In [509]:
print(a[0,0:-1:2]) # [0:-1:2] last value (2) is step, like pick element every 2 steps

[1 3 5]


In [510]:
# you can also change elements
print(a) 


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 14 16]]


In [511]:
#let's change 2 value which is a[0,1] to 50
a[0,1] = 50
print(a)

[[ 1 50  3  4  5  6  7]
 [ 8  9 10 11 12 14 16]]


In [512]:
a[:,1] = 50
print(a)

[[ 1 50  3  4  5  6  7]
 [ 8 50 10 11 12 14 16]]


In [513]:
#let's work with a 3D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [514]:
#get the value 3 in first matrix
print(c[0,1,0])

3


In [515]:
print(c[:,0,0])

[1 5]


In [516]:
#replace 3D array item
c[:,0,0] = 10

In [517]:
print(c)

[[[10  2]
  [ 3  4]]

 [[10  6]
  [ 7  8]]]


## Initializing Different Types Of Arrays

In [518]:
# Initialize all 0 Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [519]:
# Initialize all 1 matrix
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [520]:
# Initialize all 1 matrix 3D
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [521]:
# initialize matrix other numbers
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [522]:
# create matrix with existing shape
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [523]:
# initialize matrix of decimal random number
np.random.rand(4,2)

array([[0.52981058, 0.37065282],
       [0.41899222, 0.68408988],
       [0.59401398, 0.34059626],
       [0.52406675, 0.69174614]])

In [524]:
# initialize random decimal matrux using another array shape
np.random.random_sample(a.shape)

array([[0.25903386, 0.02012223, 0.28580152, 0.00454006, 0.61824343,
        0.46457035, 0.48650396],
       [0.93659861, 0.55095059, 0.42552554, 0.62389739, 0.16380078,
        0.10372501, 0.39192605]])

In [525]:
# Random integer values
np.random.randint(8,size=(3,3))

array([[7, 5, 7],
       [6, 2, 4],
       [1, 7, 1]])

In [526]:
# you can also genarate integer matrix in a range of number
np.random.randint(8,12,size=(3,3)) # here range is 8 - 12

array([[10, 11,  9],
       [ 9,  8,  8],
       [10,  9,  8]])

In [527]:
# you can also create indentity matrix
np.identity(3) # it will give us 3*3 identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [528]:
# repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0) # axis= 0 means column and axis = 1 means row
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Exercise
We are gonna create a matrix

  1 1 1 1 1
  <br>
  1 0 0 0 1
  <br>
  1 0 9 0 1
  <br>
  1 0 0 0 1
  <br>
  1 1 1 1 1

In [529]:
output = np.ones((5,5)) #first we are gonna create a 5*5 matrix of one
zero  = np.zeros((3,3)) # create a 3*3 zero matrix to fill the middle part of matrix
zero[1,1] = 9# we change the 1 row and first columm value to 9
output[1:4,1:4] = zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### careful about copying arrays

In [530]:
mainArr = np.array([1,2,3]) # first create a array
copyArr = mainArr # we are copying mainArr value to copyArr
copyArr[0] = 100 # let's change first value of copyArr to 100
print(copyArr) 
print(mainArr)
# now you see that not only copyArr, but mainArr value is also changed, because when we type copyArr = mainArr , that's means mainArr and copyArr both pointed to the same memory block where the array is stored, so when we change the value in copyArr, it changes the main array, to prevent this we are gonna use copy method
mainArr = np.array([1,2,3])
copyArr = mainArr.copy()
copyArr[0] = 100
print(mainArr)
print(copyArr)

[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


## Using numpy for mathematics

In [531]:
mathArry = np.array([1,2,3,4])
print(mathArry)

[1 2 3 4]


In [532]:
mathArry + 2 # this will add 2 with each element

array([3, 4, 5, 6])

In [533]:
mathArry - 2 # this will subtract 2 with each element

array([-1,  0,  1,  2])

In [534]:
mathArry * 2 # this will multiply 2 with each elment

array([2, 4, 6, 8])

In [535]:
mathArry / 2 # this will divid 2 with each element and give us quotient

array([0.5, 1. , 1.5, 2. ])

In [536]:
#let's add two array
mathSecondArray = np.array([2,5,3,4])
mathArry + mathSecondArray

array([3, 7, 6, 8])

In [537]:
mathArry ** 2 # we can also use exponent

array([ 1,  4,  9, 16], dtype=int32)

In [538]:
# we can also take the sin, cos and tan of all values
np.sin(mathArry)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [539]:
np.cos(mathArry)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [540]:
np.tan(mathArry)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

### linear algebra

In [541]:
# matrix multipication
linA =np.ones((2,3))
linB = np.full((3,2),2)

np.matmul(linA,linB)

array([[6., 6.],
       [6., 6.]])

In [542]:
# we can also get determinant of matrix
idMat = np.identity(3) # this will gove us 3*3 identitiy matrix
np.linalg.det(idMat)

1.0

In [543]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### statistics

In [544]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [545]:
# get the min value of data
np.min(stats)

1

In [546]:
# get the max value of data
np.max(stats)

6

In [547]:
# get the min value in row
np.min(stats,axis=1)

array([1, 4])

### reorganizing array

In [548]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [549]:
# change shape of matrix
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [551]:
# vertical statking matricies
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [552]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### load data from file

In [558]:
fileData = np.genfromtxt("data.txt",delimiter=",")
fileData =  fileData.astype("int32")# change it to intiger
fileData

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean masking and Advance Indexing

In [561]:
fileData > 50 # file data greater than 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [563]:
fileData[fileData > 50] # grab data which is greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [565]:
# you can index with a list with a numpy
a =  np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # we pass a list for indexing

array([2, 3, 9])

In [566]:
np.any(fileData> 50 ,axis = 0) # find any data greater than 50 in column

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [569]:
((fileData > 50) & (fileData < 100)) # we can use condition 

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])